/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/Drawer/Drawer.vue')['default']
    File: typeof import('./src/components/Drawer/File.vue')['default']
    Folder: typeof import('./src/components/Drawer/Folder.vue')['default']
    Graph: typeof import('./src/components/Graph/Graph.vue')['default']
    Info: typeof import('./src/components/Drawer/Info.vue')['default']
    Method: typeof import('./src/components/Drawer/Method.vue')['default']
    Visualization: typeof import('./src/components/Visualization.vue')['default']
  }
}
